name: Build PlatformIO project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./guitar-midi

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      # It is important to first install the libraries before compiling, since otherwise compilation might fail to find the just-installed libraries
      - name: Install platformIO libraries
        run: pio lib install
      - name: Build Guitar controller
        run: platformio run --environment esp32
